name: Run Pytest and Linting with Pylint and Flake8
env:
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
  SNOW_USERNAME: ${{ secrets.SF_USERNAME }}
  SNOW_PASSWORD: ${{ secrets.SF_PASSWORD }}
  SNOW_URL: ${{ secrets.SF_URL }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8

      uses: actions/setup-python@v2

      with:

        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Testing environment variable ${{ env.sf_url}} "

    - name: Run PyLint Using Custom Script with Threshold
      run: |
        python -m run_pylint.py

    - name: Run Pytest
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
        SNOW_USERNAME: ${{ secrets.SF_USERNAME }}
        SNOW_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SNOW_URL: ${{ secrets.SF_URL }}
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      run: |
        python -m pytest