name: Run Pytest and Linting with Pylint and Flake8
env:
  bucket_name: ${{ secrets.BUCKET_NAME }}
  access_key_id: ${{ secrets.ACCESS_KEY_ID }}
  aws_secret_key: ${{ secrets.ACCESS_SECRET_KEY }}
  sf_username: ${{ secrets.SF_USERNAME }}
  sf_password: ${{ secrets.SF_PASSWORD }}
  sf_url: ${{ secrets.SF_URL }}

  threshold: ${{ secrets.THRESHOLD }}

  mongo_username: ${{ secrets.MONGO_USERNAME }}
  mongo_password: ${{ secrets.MONGO_PASSWORD }}

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8

      uses: actions/setup-python@v2

      with:

        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Testing environment variable ${{ env.sf_url}} "

    - name: Run PyLint Using Custom Script with Threshold
      run: |
        python -m run_pylint.py

    # - name: Run Flake8
    #   run: |
    #     python -m flake8

    # - name: Run Pytest
    #   env:
    #     bucket_name: ${{ secrets.BUCKET_NAME }}
    #     access_key_id: ${{ secrets.ACCESS_KEY_ID }}
    #     aws_secret_key: ${{ secrets.ACCESS_SECRET_KEY }}
    #     sf_username: ${{ secrets.SF_USERNAME }}
    #     sf_password: ${{ secrets.SF_PASSWORD }}
    #     sf_url: ${{ secrets.SF_URL }}

    #     mongo_username: ${{ secrets.MONGO_USERNAME }}
    #     mongo_password: ${{ secrets.MONGO_PASSWORD }}
    #   run: |
    #     python -m pytest